name: status

on: [push]

jobs:

  lint-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Update pylint
      run: pip3 install -U pylint==2.11.0

    - name: Check pylint
      run: pylint -rn --rcfile pylintrc segfast
