name: status

on: [push]

jobs:

  lint-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update pylint
      run: pip3 install -U pylint

    - name: Check pylint
      run: pylint -rn --rcfile pylintrc segfast
